name: fake_measure
on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        description: "pull request id to put results to"
        required: false
        default: "!!not specified!!"
  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ref ${{ github.ref }}"
      - run: echo "Issue comment link ${{ github.event.inputs.issue_comment_id }}"
      - uses: octokit/request-action@v2.x
        id: updateissue
        with:
          route: POST /repos/:repository/issues/:pull_request_id/comments
          pull_request_id: ${{ github.event.inputs.pr_issue }}
          repository: ${{ github.repository }}
          body: "Some nice body on you"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
