name: fake_measure
on:
  workflow_dispatch:
    inputs:
      issue_comment_id:
        description: "issue comment id"
        required: false
        default: "!!not specified!!"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ref ${{ github.ref }}"
      - run: echo "Issue comment link ${{ github.event.inputs.issue_comment_id }}"